outputs: "./outputs"
dev: false

http:
  host: '0.0.0.0'
  port: 13000

log:
  path: './logs'
  # 日志模块会为 filename 添加相应的后缀
  filename: 'assistants'
  level: 'trace'
  rotation: '1 days'
  retention: '5 days'
  format: '<level>{level: <8}</level> <green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> - <cyan>{name}</cyan>:<cyan>{function}</cyan> - <level>{message}</level>'
